name: Expense Summary Report

on:
  workflow_dispatch:
  schedule:
    # Run on the 4,10,16,22,28th of every month at midnight
    - cron: "30 0 4,10,16,22,28 * *"

jobs:
  run-expense-report:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      # Step 1: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Step 2: Run the Python script
      - name: Run Python script
        run: |
          python mc_report.py
